name: Deploy to Github Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    if: ${{ github.repository_owner == 'rustic-rs' && github.ref == 'refs/heads/main' }}
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Build and deploy
        uses: shalzz/zola-deploy-action@960304368c31a93d6991d64ae962df0786b905f1 # v0.19.2
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD_THEMES: false
