name: Deploy to Github Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    if: ${{ github.repository_owner == 'rustic-rs' && github.ref == 'refs/heads/main' }}
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Build and deploy
        uses: shalzz/zola-deploy-action@8dd2f00cd24e36df7504aac22040a13e7f9e6d1a # v0.17.2
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD_THEMES: false
