name: Deploy to Github Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    if: ${{ github.repository_owner == 'rustic-rs' && github.ref == 'refs/heads/main' }}
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Build and deploy
        uses: shalzz/zola-deploy-action@2f512f31e2e912d5fbd15f319c9c1bfbcfa90a55 # v0.23.4
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD_THEMES: false
