name: Deploy to Github Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    if: ${{ github.repository_owner == 'rustic-rs' && github.ref == 'refs/heads/main' }}
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Build and deploy
        uses: shalzz/zola-deploy-action@c34a7626cd84c9c90499afeb310070ea838a8d1a # v0.20.0
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD_THEMES: false
